= hantemcli(1)
Gabriel Arazas
2020-01-17
:toc:
:doctype: manpage
:program: Hantemcli
:manmanual: {program} Manual
:mansource: {program} v0.2.0

:binary-name: hantemcli
:template-file-ext: hbs




== Name 

{binary-name} - a basic application for rendering Handlebars templates with data files (i.e., JSON, YAML, HJSON, INI, TOML). 




== Sypnosis 

*{binary-name}* [_GLOBAL OPTIONS_] [_TEMPLATE FILES_]... -- [_DATA FILES_]...




== Global options 

*-o, --output*=[_PATH_]:: 
The output file to be written. 

*-r, --root*=[_TEMPLATE NAME_]:: 
The template name in the registry to be rendered. 

*-e, --extension*=[_FILE EXTENSION_]:: 
The file extension of the template files to be searched. 
By default, it has `hbs` as the value. 

*-s, --strict*:: 
Set the renderer in strict mode where it will give an error for a missing value. 




== Examples 

Some quick examples of using {program}. 

[source, shell]
----
# Render the template in `tests/base.hbs` with the data from `tests/default.toml`
hantemcli tests/base.hbs -- tests/default.toml
----

[source, shell]
----
# Render a template that uses partials. 
# Assume that 'tests/base.hbs' includes a partial with 'tests/template.hbs'. 

# The '--root'/'-r' option is the name of the template to be rendered. 
# By default, the program will render the alphabetically first template in the registry. 
hantemcli --root base tests/base.hbs tests/template.hbs -- tests/default.toml
----

[source, shell]
----
# The program can also accept a directory for convenience. 
# By default, it searches for all of the files with the `.hbs` extension. 
hantemcli --root base tests/ -- tests/default.toml
----

[source, shell]
----
# Render with custom file extensions. 
# It will also ignore if the given argument file is not valid with the file extension. 
hantemcli --root base --extension .tex.hbs tests/ tests/default.hbs -- tests/default.toml
----




== User guide 

{program} is a simple Handlebars template renderer for the command line. 
It is inspired from other command line template renderers such as https://github.com/subfuzion/envtpl/[envtpl] and https://github.com/quitoque/hdlbr[hdlbr]. 
In this case, {program} tries to stand out by allowing you to render templates with multiple files along with enforcing some conventions. 
This is particularly useful for simple use cases such as quickly rendering text files/configuration files. 
footnote:[In my case, I use to render LaTeX files with certain data files.]

Consider the examples with this particular folder structure. 

[source]
----
tests
├── base.hbs
├── default.toml
├── dev.toml
├── prod.toml
├── template.hbs
├── test2.json
└── test.json
----

First basic example: a basic template with a data file. 

[source, shell]
----
hantemcli tests/template.hbs -- tests/default.toml
----

This also introduces one of the restrictions: {program} only accepts template files with the '{template-file-ext}' file extension. 

Registering multiple templates is also possible. 
This is required if you want to make use of https://handlebarsjs.com/guide/#partials[partials] and create skeleton templates. 

Internally, the files are registered in a key-value store with the filename as the key. 
In the previous example shell command, the file `tests/template.hbs` is registered simply as `template`. 

{program} can also accept a directory for the location of the templates. 
This will register all of the template files in the directory and its subdirectories with their keys set to the relative path from the given directory — e.g., `tests/template.hbs` will be registered as `template` if the given argument is `./tests` and the file exists. 

We can only render one template in a command. 
To set the template to be rendered (also referred to as the *root template*), you can set the `-r`/`--root` option and give the template name in the key-value store. 
If this option is not set, it will render the template that is alphabetically first in the template store. 
In this example, we render the template named 'base' in the resulting registry (which is the one to be rendered if the option is unset anyway) considering with all of the TOML data files. 

[source, shell]
----
# This will result in the same rendered template (with the example folder structure).
hantemcli --root base tests/template.hbs tests/base.hbs -- tests/default.toml

hantemcli --root base tests/ -- tests/default.toml

hantemcli --root tests/base ./ -- tests/default.toml
----

As said previously, {program} accepts data files of various formats as long it is results into a hash table/associative array. 
As of 2020-01-29, the data formats that {program} accepts are in JSON, HJSON, INI, TOML, and YAML format. 
Similar to template files, {program} only accepts certain files with valid file extensions (e.g., '.toml' for TOML files, '.json' for JSON files, '.yaml' for YAML files). 

[source, shell]
----
hantemcli --root base tests/ -- $(ls tests/*.toml) $(ls tests/*.json)
----

The data from those files are then merged starting with the first given data file in the command. 
In the above example, we render the template named 'base' in the registry with all of the data files. 
It will start to merge with the first data file (`tests/default.toml`) then the second (`tests/dev.toml`), third (`tests/prod.toml`), and so on. 

The renderer can also be set in strict mode. 
In this mode, it will give an error for a missing value. 
This is useful for ensuring the template is fully rendered as intended. 
Although, missing partials are not included in the error-checking process. 

[source, shell]
----
# May or may not return an error depending if the resulting data from the data file(s) is complete. 
hantemcli --root template --strict tests/ -- tests/default.toml
----




== Exit codes 

**0**:: 
Termination has been successful. 

**1**:: 
An error occurred (i.e., file creation error, template rendering error). 




== Repository 

Git repo: https://github.com/foo-dogsquared/hantemcli

Issues: https://github.com/foo-dogsquared/hantemcli/issues

